app/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()


class Employee(db.Model, UserMixin):  # Your class definition
    # Mapping attributes, here
    __tablename__ = "employees"
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100), nullable=False)
    employee_number = db.Column(db.Integer, nullable=False, unique=True)
    hashed_password = db.Column(db.String(255), nullable=False)

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)


class Menu(db.Model):
    __tablename__ = "menus"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(30), nullable=False)

    items = db.relationship("MenuItem", back_populates="menus") # "menus" should refer to field on child


class MenuItem(db.Model):
    __tablename__ = "menu_items"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), nullable=False)
    price = db.Column(db.Float, nullable=False)

    menu_id = db.Column(db.Integer, db.ForeignKey("menus.id"), nullable=False)
    menu_type_id = db.Column(db.Integer, db.ForeignKey("menu_item_types.id"))

    menus = db.relationship("Menu")
    types = db.relationship("MenuItemType")


class MenuItemType(db.Model):
    __tablename__ = "menu_item_types"
    
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    
    items = db.relationship("MenuItem", back_populates="types")


class Table(db.Model):
    __tablename__ = "tables"
    
    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.Integer, nullable=False, unique=True)
    capacity = db.Column(db.Integer, nullable=False)


class Order(db.Model):
    __tablename__ = "orders"
    
    id = db.Column(db.Integer, primary_key=True)
    employee_id = db.Column(db.Integer, db.ForeignKey("employees.id"), nullable=False)
    table_id = db.Column(db.Integer, db.ForeignKey("tables.id"), nullable=False)
    finished = db.Column(db.Boolean, nullable=False)


class OrderDetail(db.Model):
    __tablename__ = "order_details"
    
    id = db.Column(db.Integer, primary_key=True)
    order_id = db.Column(db.Integer, db.ForeignKey("orders.id"), nullable=False)
    menu_item_id = db.Column(db.Integer, db.ForeignKey("menu_items.id"), nullable=False)

app/forms.py
from wtforms.fields import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf import FlaskForm

class LoginForm(FlaskForm):
    employee_number = StringField(validators=[DataRequired()], label="Employee Number")
    password = PasswordField(validators=[DataRequired()], label="Password")
    submit = SubmitField(label="Login")

app/__init__.py
from flask import Flask
from .config import Configuration
from .models import db, Employee
from .routes import orders, session
from flask_login import LoginManager


app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)
db.init_app(app)  # Configure the application with SQLAlchemy


login = LoginManager(app)
login.login_view = "session.login"

@login.user_loader
def load_user(id):
    return Employee.query.get(int(id))

app/routes/orders.py
from flask import Blueprint, render_template
from flask_login import login_required


bp = Blueprint("orders", __name__, url_prefix="")


@bp.route("/")
@login_required
def index():
    return render_template("orders.html")

app/routes/session.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user
from app.forms import LoginForm
from app.models import Employee

bp = Blueprint("session", __name__, url_prefix="/session")

# The use of @bp, here, assumes you named the variable "bp"
# that holds your Blueprint object for this routing module
@bp.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("orders.index"))
    form = LoginForm()
    if form.validate_on_submit():
        empl_number = form.employee_number.data
        employee = Employee.query.filter(Employee.employee_number == empl_number).first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for(".login"))
        login_user(employee)
        return redirect(url_for("orders.index"))
    return render_template("login.html", form=form)
    
    
@bp.route('/logout', methods=["POST"])
def logout():
    logout_user()
    return redirect(url_for('.login'))

app/templates/base.html
<html>

    <head>
        {% if title %}
        <title>{{ title }} - Order Up!</title>
        {% else %}
        <title>Welcome to Order Up!</title>
        {% endif %}
    </head>

    <body>
        {% if not current_user.is_anonymous %}
        <form method="post" action="{{ url_for('session.logout') }}" id="logout"></form>
        <button type="submit" form="logout">Logout</button>
        {% endif %}
        {% block content %}{% endblock %}
    </body>

</html>

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{{ url_for('.login') }}">
    {{ form.csrf_token }}
    <div>
        {{ form.employee_number.label }} {{ form.employee_number }}

        {% if form.employee_number.errors %}
        <ul>
            {% for error in form.employee_number.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>
        {{ form.password.label }} {{ form.password }}

        {% if form.employee_number.errors %}
        <ul>
            {% for error in form.employee_number.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    <div>{{ form.submit }}</div>
</form>
{% endblock %}

app/templates/orders.html
{% extends "base.html" %}

{% block content %}
<h1>Order Up!</h1>
{% endblock %}